version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres-spring
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github-actions-spring
    ports:
      - "5432:5432"
